// import things from "../images/things-fall-apart.jpg";

export const bookLists = [
  {
    id: crypto.randomUUID(),
    author: "Chinua Achebe",
    country: "Nigeria",
    imageLink: "./images/things-fall-apart.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Things_Fall_Apart\n",
    pages: 209,
    title: "Things Fall Apart",
    year: 1958,
    isFavourite: false,
  },
  {
    id: crypto.randomUUID(),
    author: "Hans Christian Andersen",
    country: "Denmark",
    imageLink: "./images/fairy-tales.jpg",
    language: "Danish",
    link: "https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.\n",
    pages: 784,
    title: "Fairy tales",
    year: 1836,
    isFavourite: false,
  },
  {
    id: crypto.randomUUID(),
    author: "Dante Alighieri",
    country: "Italy",
    imageLink: "./images/the-divine-comedy.jpg",
    language: "Italian",
    link: "https://en.wikipedia.org/wiki/Divine_Comedy\n",
    pages: 928,
    title: "The Divine Comedy",
    year: 1315,
    isFavourite: false,
  },
  {
    id: crypto.randomUUID(),
    author: "Robert Musil",
    country: "Austria",
    imageLink: "./images/the-man-without-qualities.jpg",
    language: "German",
    link: "https://en.wikipedia.org/wiki/The_Man_Without_Qualities\n",
    pages: 365,
    title: "The Man Without Qualities",
    year: 1931,
  },
  {
    id: crypto.randomUUID(),
    author: "Vladimir Nabokov",
    country: "Russia/United States",
    imageLink: "./images/lolita.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Lolita\n",
    pages: 317,
    title: "Lolita",
    year: 1955,
  },
  {
    id: crypto.randomUUID(),
    author: "George Orwell",
    country: "United Kingdom",
    imageLink: "./images/nineteen-eighty-four.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Nineteen_Eighty-Four\n",
    pages: 272,
    title: "Nineteen Eighty-Four",
    year: 1949,
  },
  {
    id: crypto.randomUUID(),
    author: "Ovid",
    country: "Roman Empire",
    imageLink: "./images/the-metamorphoses-of-ovid.jpg",
    language: "Classical Latin",
    link: "https://en.wikipedia.org/wiki/Metamorphoses\n",
    pages: 576,
    title: "Metamorphoses",
    year: 100,
  },
  {
    id: crypto.randomUUID(),
    author: "Jane Austen",
    country: "United Kingdom",
    imageLink: "./images/pride-and-prejudice.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Pride_and_Prejudice\n",
    pages: 226,
    title: "Pride and Prejudice",
    year: 1813,
    isFavourite: false,
  },
  {
    id: crypto.randomUUID(),
    author: "Honor\u00e9 de Balzac",
    country: "France",
    imageLink: "./images/le-pere-goriot.jpg",
    language: "French",
    link: "https://en.wikipedia.org/wiki/Le_P%C3%A8re_Goriot\n",
    pages: 443,
    title: "Le P\u00e8re Goriot",
    year: 1835,
    isFavourite: false,
  },
  {
    id: crypto.randomUUID(),
    author: "Samuel Beckett",
    country: "Republic of Ireland",
    imageLink: "./images/molloy-malone-dies-the-unnamable.jpg",
    language: "French, English",
    link: "https://en.wikipedia.org/wiki/Molloy_(novel)\n",
    pages: 256,
    title: "Molloy, Malone Dies, The Unnamable, the trilogy",
    year: 1952,
    isFavourite: false,
  },
  {
    id: crypto.randomUUID(),
    author: "Giovanni Boccaccio",
    country: "Italy",
    imageLink: "./images/the-decameron.jpg",
    language: "Italian",
    link: "https://en.wikipedia.org/wiki/The_Decameron\n",
    pages: 1024,
    title: "The Decameron",
    year: 1351,
    isFavourite: false,
  },
  {
    id: crypto.randomUUID(),
    author: "Jorge Luis Borges",
    country: "Argentina",
    imageLink: "./images/ficciones.jpg",
    language: "Spanish",
    link: "https://en.wikipedia.org/wiki/Ficciones\n",
    pages: 224,
    title: "Ficciones",
    year: 1965,
    isFavourite: false,
  },
  {
    id: crypto.randomUUID(),
    author: "Emily Bront\u00eb",
    country: "United Kingdom",
    imageLink: "./images/wuthering-heights.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Wuthering_Heights\n",
    pages: 342,
    title: "Wuthering Heights",
    year: 1847,
    isFavourite: false,
  },
  {
    id: crypto.randomUUID(),
    author: "Albert Camus",
    country: "Algeria, French Empire",
    imageLink: "./images/l-etranger.jpg",
    language: "French",
    link: "https://en.wikipedia.org/wiki/The_Stranger_(novel)\n",
    pages: 185,
    title: "The Stranger",
    year: 1942,
    isFavourite: false,
  },
  {
    id: crypto.randomUUID(),
    author: "Paul Celan",
    country: "Romania, France",
    imageLink: "./images/poems-paul-celan.jpg",
    language: "German",
    link: "\n",
    pages: 320,
    title: "Poems",
    year: 1952,
    isFavourite: false,
  },
  {
    id: crypto.randomUUID(),
    author: "Louis-Ferdinand C\u00e9line",
    country: "France",
    imageLink: "./images/voyage-au-bout-de-la-nuit.jpg",
    language: "French",
    link: "https://en.wikipedia.org/wiki/Journey_to_the_End_of_the_Night\n",
    pages: 505,
    title: "Journey to the End of the Night",
    year: 1932,
    isFavourite: false,
  },
];
